import { useEffect, useState } from "react";
import type { Account, SavingGoal, SavingGoalPayload } from "../types/finance";
import Modal from "./Modal";

const field = "mt-1.5 w-full rounded-2xl border border-slate-200 bg-white px-3.5 py-3 text-sm font-medium outline-none focus:border-[var(--accent)] dark:border-slate-700 dark:bg-slate-950 dark:text-white";
const label = "text-xs font-bold uppercase tracking-[0.12em] text-slate-400";
const COLORS=["#7059f5","#3569ff","#169b78","#f59e0b","#ef4444"];

export default function GoalModal({open, goal, accounts, onClose, onSubmit}:{open:boolean;goal:SavingGoal|null;accounts:Account[];onClose:()=>void;onSubmit:(payload:SavingGoalPayload)=>Promise<void>}){
  const [name,setName]=useState("");const [target,setTarget]=useState("");const [current,setCurrent]=useState("0.00");const [date,setDate]=useState("");const [accountId,setAccountId]=useState("");const [color,setColor]=useState(COLORS[0]);const [saving,setSaving]=useState(false);
  useEffect(()=>{if(!open)return;setName(goal?.name??"");setTarget(goal?.target_amount??"");setCurrent(goal?.current_amount??"0.00");setDate(goal?.target_date??"");setAccountId(goal?.account_id?.toString()??"");setColor(goal?.color??COLORS[0]);},[open,goal]);
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);try{await onSubmit({name,target_amount:target,current_amount:current,target_date:date||null,account_id:accountId?Number(accountId):null,color});onClose();}finally{setSaving(false)}}
  return <Modal open={open} title={goal?"Modifier l’objectif":"Nouvel objectif"} subtitle="Crée une cible d’épargne et suis ta progression." onClose={onClose}><form onSubmit={submit} className="space-y-4"><label className="block"><span className={label}>Nom</span><input className={field} required value={name} onChange={(e)=>setName(e.target.value)} placeholder="Voyage Japon"/></label><div className="grid gap-4 sm:grid-cols-2"><label><span className={label}>Cible</span><input className={field} required type="number" min="0.01" step="0.01" value={target} onChange={(e)=>setTarget(e.target.value)}/></label><label><span className={label}>Déjà épargné</span><input className={field} type="number" min="0" step="0.01" value={current} onChange={(e)=>setCurrent(e.target.value)}/></label></div><div className="grid gap-4 sm:grid-cols-2"><label><span className={label}>Date cible</span><input className={field} type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></label><label><span className={label}>Compte associé</span><select className={field} value={accountId} onChange={(e)=>setAccountId(e.target.value)}><option value="">Aucun</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><div><span className={label}>Couleur</span><div className="mt-3 flex gap-2">{COLORS.map(value=><button type="button" key={value} onClick={()=>setColor(value)} className={`size-9 rounded-xl border-2 ${color===value?"border-slate-950 dark:border-white":"border-transparent"}`} style={{backgroundColor:value}}/>)}</div></div><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-2xl px-4 py-3 text-sm font-bold text-slate-500">Annuler</button><button disabled={saving} className="rounded-2xl bg-[var(--accent)] px-5 py-3 text-sm font-black text-white">Enregistrer</button></div></form></Modal>
}
