import type { Account } from "../types/finance";
import { accountTypeLabel, formatCurrency } from "../utils/format";
import EmptyState from "../components/EmptyState";
import Icon from "../components/Icon";
import PageHeader from "../components/PageHeader";

export default function AccountsPage({accounts,onAdd,onEdit,onArchive}:{accounts:Account[];onAdd:()=>void;onEdit:(a:Account)=>void;onArchive:(a:Account)=>void;}){
  const total=accounts.reduce((sum,a)=>sum+Number(a.balance),0);
  return <><PageHeader eyebrow="Patrimoine" title="Comptes" description="Tes comptes sont le socle de Home Budget : courant, épargne, espèces ou crédit." action={<button onClick={onAdd} className="rounded-2xl bg-[var(--accent)] px-4 py-3 text-sm font-black text-white">+ Nouveau compte</button>}/><div className="mb-5 rounded-[28px] bg-slate-950 p-6 text-white shadow-xl dark:bg-white dark:text-slate-950"><p className="text-xs font-bold uppercase tracking-[0.18em] opacity-60">Patrimoine net suivi</p><p className="mt-2 text-4xl font-black tracking-tight">{formatCurrency(total)}</p><p className="mt-2 text-sm opacity-60">Somme des soldes actuels de tes comptes actifs.</p></div>{accounts.length===0?<EmptyState title="Crée ton premier compte" description="Ajoute par exemple ton compte courant, puis ton livret ou tes espèces."/>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{accounts.map(account=><article key={account.id} className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="absolute -right-8 -top-8 size-28 rounded-full opacity-10" style={{backgroundColor:account.color}}/><div className="relative flex items-start justify-between"><div className="grid size-11 place-items-center rounded-2xl text-white" style={{backgroundColor:account.color}}><Icon name="wallet" className="size-5"/></div><div className="flex gap-1"><button onClick={()=>onEdit(account)} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><Icon name="edit" className="size-4"/></button><button onClick={()=>onArchive(account)} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" title="Archiver"><Icon name="archive" className="size-4"/></button></div></div><p className="mt-6 text-sm font-bold text-slate-500">{accountTypeLabel(account.type)}</p><h2 className="mt-1 text-xl font-black text-slate-950 dark:text-white">{account.name}</h2><p className={`mt-6 text-3xl font-black tracking-tight ${Number(account.balance)<0?"text-rose-600":"text-slate-950 dark:text-white"}`}>{formatCurrency(account.balance,account.currency)}</p><p className="mt-2 text-xs text-slate-400">Solde initial : {formatCurrency(account.opening_balance,account.currency)}</p></article>)}</div>}</>;
}
