import type { SavingGoal } from "../types/finance";
import { formatCurrency, formatDate } from "../utils/format";
import EmptyState from "../components/EmptyState";
import Icon from "../components/Icon";
import PageHeader from "../components/PageHeader";

export default function GoalsPage({goals,onAdd,onEdit,onDelete}:{goals:SavingGoal[];onAdd:()=>void;onEdit:(goal:SavingGoal)=>void;onDelete:(goal:SavingGoal)=>void;}){
 return <><PageHeader eyebrow="Épargne" title="Objectifs" description="Transforme tes projets en cibles visibles et mesurables." action={<button onClick={onAdd} className="rounded-2xl bg-[var(--accent)] px-4 py-3 text-sm font-black text-white">+ Nouvel objectif</button>}/>{goals.length===0?<EmptyState title="Aucun objectif" description="Vacances, voiture, apport, fonds d’urgence : commence par une cible qui compte pour toi."/>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{goals.map(goal=>{const progress=Math.min(Number(goal.progress_percentage),100);return <article key={goal.id} className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-2xl text-white" style={{backgroundColor:goal.color}}><Icon name="target" className="size-5"/></div><div className="flex gap-1"><button onClick={()=>onEdit(goal)} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><Icon name="edit" className="size-4"/></button><button onClick={()=>onDelete(goal)} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-950/30"><Icon name="trash" className="size-4"/></button></div></div><h2 className="mt-5 text-xl font-black text-slate-950 dark:text-white">{goal.name}</h2><div className="mt-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">Progression</p><p className="mt-1 text-2xl font-black text-slate-950 dark:text-white">{formatCurrency(goal.current_amount)}</p></div><p className="text-sm font-black text-slate-500">/ {formatCurrency(goal.target_amount)}</p></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full" style={{width:`${progress}%`,backgroundColor:goal.color}}/></div><div className="mt-3 flex justify-between text-xs font-bold text-slate-400"><span>{Number(goal.progress_percentage).toLocaleString("fr-FR",{maximumFractionDigits:1})}%</span><span>{goal.target_date?formatDate(goal.target_date):"Sans échéance"}</span></div></article>})}</div>}</>;
}
