import type { RecurringTransaction } from "../types/finance";
import { formatCurrency, formatDate, transactionTypeLabel } from "../utils/format";
import EmptyState from "../components/EmptyState";
import Icon from "../components/Icon";
import PageHeader from "../components/PageHeader";
import Panel from "../components/Panel";

const frequencyLabel={weekly:"Chaque semaine",monthly:"Chaque mois",yearly:"Chaque année"} as const;
export default function RecurringPage({items,onAdd,onEdit,onDelete,onGenerate}:{items:RecurringTransaction[];onAdd:()=>void;onEdit:(item:RecurringTransaction)=>void;onDelete:(item:RecurringTransaction)=>void;onGenerate:()=>void;}){
 return <><PageHeader eyebrow="Automatisation" title="Récurrences" description="Prépare loyer, abonnements, salaire et transferts réguliers." action={<div className="flex gap-2"><button onClick={onGenerate} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-black text-slate-700 dark:border-slate-700 dark:bg-slate-900 dark:text-white">Générer les échéances</button><button onClick={onAdd} className="rounded-2xl bg-[var(--accent)] px-4 py-3 text-sm font-black text-white">+ Récurrence</button></div>}/><Panel className="overflow-hidden">{items.length===0?<EmptyState title="Aucune récurrence" description="Ajoute une charge fixe ou un revenu régulier pour gagner du temps chaque mois."/>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{items.map(item=><div key={item.id} className="flex flex-col gap-4 px-6 py-5 sm:flex-row sm:items-center"><div className={`grid size-11 place-items-center rounded-2xl ${item.type==="income"?"bg-emerald-50 text-emerald-600 dark:bg-emerald-950/30":item.type==="expense"?"bg-rose-50 text-rose-600 dark:bg-rose-950/30":"bg-sky-50 text-sky-600 dark:bg-sky-950/30"}`}><Icon name="recurring" className="size-5"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-black text-slate-900 dark:text-white">{item.name}</p>{!item.is_active?<span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-black uppercase text-slate-400 dark:bg-slate-800">Pause</span>:null}</div><p className="mt-1 text-xs text-slate-400">{transactionTypeLabel(item.type)} · {frequencyLabel[item.frequency]} · prochaine le {formatDate(item.next_date)}</p></div><p className="text-lg font-black text-slate-950 dark:text-white">{formatCurrency(item.amount)}</p><div className="flex gap-1"><button onClick={()=>onEdit(item)} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><Icon name="edit" className="size-4"/></button><button onClick={()=>onDelete(item)} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-950/30"><Icon name="trash" className="size-4"/></button></div></div>)}</div>}</Panel></>;
}
